using System;
using PSXAPI.Response;
using UnityEngine;

// Token: 0x0200020D RID: 525
public class IBJOGQJFQEP : MonoBehaviour
{
	// Token: 0x060045F8 RID: 17912 RVA: 0x0021CF78 File Offset: 0x0021B178
	public void KHGKJOLKFGK(LootVote KOEEIBDFFGE)
	{
		LCBQFQDLLEB component = this.JHDGENGBPQF.gameObject.BFCKNMFEBDM(this.QMMMEOKMMGD).GetComponent<LCBQFQDLLEB>();
		component.CLBHJLICGPC = UnityEngine.Time.time;
		component.ICFJOIPHKDJ = (float)KOEEIBDFFGE.Duration.TotalSeconds;
		component.JHDGENGBPQF = this.JHDGENGBPQF;
		component.DBPKNCDGGEP = KOEEIBDFFGE.VoteID;
		component.GDQHOCHHIJD.KJGMGPCEJJD = 190;
		component.NKKMJICKKLB.LKPOBCBOFIC(KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.ItemID).Name);
		component.PHMFEMBPQLN.GOIHJQNMMJD = GFHGEJNHLFQ.QOQONHOOLNE.QDMQEBHOENL(KOEEIBDFFGE.ItemID.ToString());
		this.JHDGENGBPQF.PFEIQDIJEKE();
	}

	// Token: 0x060045F9 RID: 17913 RVA: 0x0001DA9A File Offset: 0x0001BC9A
	private void LFJEJGOMLPI()
	{
		IBJOGQJFQEP.HBFFCJHOCPE = this;
	}

	// Token: 0x060045FA RID: 17914 RVA: 0x0001DAA2 File Offset: 0x0001BCA2
	public static IBJOGQJFQEP DGCQMNHFQNH()
	{
		return IBJOGQJFQEP.HBFFCJHOCPE;
	}

	// Token: 0x060045FB RID: 17915 RVA: 0x0021D038 File Offset: 0x0021B238
	public void IDQFFCIDNDN(Loot KOEEIBDFFGE)
	{
		if (KOEEIBDFFGE.Result == LootVoteResult.Passed)
		{
			CNCJKLNHQBH.BJLGEDCPENQ().MIDPIFHNNDK("," + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).FLFQBGJQBBD() + "[-]!\r\n");
		}
		else if (KOEEIBDFFGE.Result == LootVoteResult.TimedOut)
		{
			CNCJKLNHQBH.MOGQNGEPCEO().MIDPIFHNNDK("!\r\n" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).FLFQBGJQBBD() + "Rivalry");
		}
		else if (KOEEIBDFFGE.Result == (LootVoteResult)8)
		{
			CNCJKLNHQBH.MOGQNGEPCEO().GQOBKDLOCDL("_Texture0" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).Name + "gluttony");
		}
		else if (KOEEIBDFFGE.Result == LootVoteResult.TimedOut)
		{
			CNCJKLNHQBH.QOQONHOOLNE.MIDPIFHNNDK("Login" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).FLFQBGJQBBD() + "Natural Cure");
		}
		if (KOEEIBDFFGE.Result != LootVoteResult.Won)
		{
			CNCJKLNHQBH.MOGQNGEPCEO().GQOBKDLOCDL(KOEEIBDFFGE.Winner + "FOG_OFF" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).Name + "System");
		}
	}

	// Token: 0x060045FC RID: 17916 RVA: 0x0021D168 File Offset: 0x0021B368
	public void COEOGLQNIMP(LootVote KOEEIBDFFGE)
	{
		LCBQFQDLLEB component = this.JHDGENGBPQF.gameObject.BFCKNMFEBDM(this.QMMMEOKMMGD).GetComponent<LCBQFQDLLEB>();
		component.CLBHJLICGPC = UnityEngine.Time.time;
		component.ICFJOIPHKDJ = (float)KOEEIBDFFGE.Duration.TotalSeconds;
		component.JHDGENGBPQF = this.JHDGENGBPQF;
		component.DBPKNCDGGEP = KOEEIBDFFGE.VoteID;
		component.GDQHOCHHIJD.KJGMGPCEJJD = -121;
		component.NKKMJICKKLB.PIDLOFMIEFQ = KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.ItemID).NDPGCGDLEEQ();
		component.PHMFEMBPQLN.GOIHJQNMMJD = GFHGEJNHLFQ.GGBPGMMCGLI().QDMQEBHOENL(KOEEIBDFFGE.ItemID.ToString());
		this.JHDGENGBPQF.Reposition();
	}

	// Token: 0x060045FD RID: 17917 RVA: 0x0021D228 File Offset: 0x0021B428
	public void QDIGCNNQBLE(Loot KOEEIBDFFGE)
	{
		if (KOEEIBDFFGE.Result == LootVoteResult.Passed)
		{
			CNCJKLNHQBH.MOGQNGEPCEO().MIDPIFHNNDK("_UserLut_Params" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).DFNQHDEDDKE() + " can't use the move!\r\n");
		}
		else if (KOEEIBDFFGE.Result == LootVoteResult.TimedOut)
		{
			CNCJKLNHQBH.MOGQNGEPCEO().GQOBKDLOCDL("-fieldstart" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).FLFQBGJQBBD() + "(R)");
		}
		else if (KOEEIBDFFGE.Result == LootVoteResult.Passed)
		{
			CNCJKLNHQBH.QOQONHOOLNE.GQOBKDLOCDL("Female Pokemon Rate Increased.\nTriggers: [2ecc71]Cute Charm[-]" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).DFNQHDEDDKE() + " requires ");
		}
		else if (KOEEIBDFFGE.Result == LootVoteResult.TimedOut)
		{
			CNCJKLNHQBH.MOGQNGEPCEO().GQOBKDLOCDL("The rainbow on " + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).FLFQBGJQBBD() + "After your payment has been verified your Lootboxes will be added to your account.");
		}
		if (KOEEIBDFFGE.Result != LootVoteResult.Won)
		{
			CNCJKLNHQBH.MOGQNGEPCEO().GQOBKDLOCDL(KOEEIBDFFGE.Winner + "ENABLE_BLUE_CHANNEL" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).Name + "l");
		}
	}

	// Token: 0x060045FE RID: 17918 RVA: 0x0001DAA2 File Offset: 0x0001BCA2
	public static IBJOGQJFQEP QBNCFLKLLKC()
	{
		return IBJOGQJFQEP.HBFFCJHOCPE;
	}

	// Token: 0x060045FF RID: 17919 RVA: 0x0001DAA2 File Offset: 0x0001BCA2
	public static IBJOGQJFQEP DQLDEKPLECH()
	{
		return IBJOGQJFQEP.HBFFCJHOCPE;
	}

	// Token: 0x06004600 RID: 17920 RVA: 0x0001DA9A File Offset: 0x0001BC9A
	private void OEEPBOFIEQF()
	{
		IBJOGQJFQEP.HBFFCJHOCPE = this;
	}

	// Token: 0x06004601 RID: 17921 RVA: 0x0021D358 File Offset: 0x0021B558
	public void EPFNKDNNPDK(Loot KOEEIBDFFGE)
	{
		if (KOEEIBDFFGE.Result == (LootVoteResult)5)
		{
			CNCJKLNHQBH.BJLGEDCPENQ().MIDPIFHNNDK("Reflect made " + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).NDPGCGDLEEQ() + "default");
		}
		else if (KOEEIBDFFGE.Result == LootVoteResult.TimedOut)
		{
			CNCJKLNHQBH.BJLGEDCPENQ().GQOBKDLOCDL("[PD]" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).JQBDPHILQJO() + "stamina");
		}
		else if (KOEEIBDFFGE.Result == (LootVoteResult)5)
		{
			CNCJKLNHQBH.QOQONHOOLNE.MIDPIFHNNDK("replace" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).NDPGCGDLEEQ() + "'s ");
		}
		else if (KOEEIBDFFGE.Result == LootVoteResult.TimedOut)
		{
			CNCJKLNHQBH.MOGQNGEPCEO().GQOBKDLOCDL("VolumetricFogAndMist/VolumetricFog" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).Name + "any");
		}
		if (KOEEIBDFFGE.Result != LootVoteResult.TimedOut)
		{
			CNCJKLNHQBH.MOGQNGEPCEO().MIDPIFHNNDK(KOEEIBDFFGE.Winner + ".wav" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).JQBDPHILQJO() + "Take 001");
		}
	}

	// Token: 0x06004602 RID: 17922 RVA: 0x0021D488 File Offset: 0x0021B688
	public void CQHFLKNNLGC(LootVote KOEEIBDFFGE)
	{
		LCBQFQDLLEB component = this.JHDGENGBPQF.gameObject.BFCKNMFEBDM(this.QMMMEOKMMGD).GetComponent<LCBQFQDLLEB>();
		component.CLBHJLICGPC = UnityEngine.Time.time;
		component.ICFJOIPHKDJ = (float)KOEEIBDFFGE.Duration.TotalSeconds;
		component.JHDGENGBPQF = this.JHDGENGBPQF;
		component.DBPKNCDGGEP = KOEEIBDFFGE.VoteID;
		component.GDQHOCHHIJD.KJGMGPCEJJD = 15;
		component.NKKMJICKKLB.LKPOBCBOFIC(KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.ItemID).Name);
		component.PHMFEMBPQLN.GOIHJQNMMJD = GFHGEJNHLFQ.QOQONHOOLNE.PINEJNIDONB(KOEEIBDFFGE.ItemID.ToString());
		this.JHDGENGBPQF.Reposition();
	}

	// Token: 0x06004603 RID: 17923 RVA: 0x0021D548 File Offset: 0x0021B748
	public void NQBNQGIFLBN(LootVote KOEEIBDFFGE)
	{
		LCBQFQDLLEB component = this.JHDGENGBPQF.gameObject.BFCKNMFEBDM(this.QMMMEOKMMGD).GetComponent<LCBQFQDLLEB>();
		component.CLBHJLICGPC = UnityEngine.Time.time;
		component.ICFJOIPHKDJ = (float)KOEEIBDFFGE.Duration.TotalSeconds;
		component.JHDGENGBPQF = this.JHDGENGBPQF;
		component.DBPKNCDGGEP = KOEEIBDFFGE.VoteID;
		component.GDQHOCHHIJD.KJGMGPCEJJD = -149;
		component.NKKMJICKKLB.LKPOBCBOFIC(KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.ItemID).Name);
		component.PHMFEMBPQLN.GOIHJQNMMJD = GFHGEJNHLFQ.GGBPGMMCGLI().OKBJNLOPPBF(KOEEIBDFFGE.ItemID.ToString());
		this.JHDGENGBPQF.PFEIQDIJEKE();
	}

	// Token: 0x06004604 RID: 17924 RVA: 0x0021D608 File Offset: 0x0021B808
	public void EJQDMONFHGM(LootVote KOEEIBDFFGE)
	{
		LCBQFQDLLEB component = this.JHDGENGBPQF.gameObject.BFCKNMFEBDM(this.QMMMEOKMMGD).GetComponent<LCBQFQDLLEB>();
		component.CLBHJLICGPC = UnityEngine.Time.time;
		component.ICFJOIPHKDJ = (float)KOEEIBDFFGE.Duration.TotalSeconds;
		component.JHDGENGBPQF = this.JHDGENGBPQF;
		component.DBPKNCDGGEP = KOEEIBDFFGE.VoteID;
		component.GDQHOCHHIJD.KJGMGPCEJJD = 17;
		component.NKKMJICKKLB.PIDLOFMIEFQ = KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.ItemID).Name;
		component.PHMFEMBPQLN.GOIHJQNMMJD = GFHGEJNHLFQ.GGBPGMMCGLI().PINEJNIDONB(KOEEIBDFFGE.ItemID.ToString());
		this.JHDGENGBPQF.Reposition();
	}

	// Token: 0x06004605 RID: 17925 RVA: 0x0021D6C8 File Offset: 0x0021B8C8
	public void DKJGNBBDOEC(LootVote KOEEIBDFFGE)
	{
		LCBQFQDLLEB component = this.JHDGENGBPQF.gameObject.BFCKNMFEBDM(this.QMMMEOKMMGD).GetComponent<LCBQFQDLLEB>();
		component.CLBHJLICGPC = UnityEngine.Time.time;
		component.ICFJOIPHKDJ = (float)KOEEIBDFFGE.Duration.TotalSeconds;
		component.JHDGENGBPQF = this.JHDGENGBPQF;
		component.DBPKNCDGGEP = KOEEIBDFFGE.VoteID;
		component.GDQHOCHHIJD.KJGMGPCEJJD = 138;
		component.NKKMJICKKLB.PIDLOFMIEFQ = KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.ItemID).FLFQBGJQBBD();
		component.PHMFEMBPQLN.GOIHJQNMMJD = GFHGEJNHLFQ.BEKHPOHIPDE().QDMQEBHOENL(KOEEIBDFFGE.ItemID.ToString());
		this.JHDGENGBPQF.Reposition();
	}

	// Token: 0x06004606 RID: 17926 RVA: 0x0021D788 File Offset: 0x0021B988
	public void FKEMCNOKHDK(LootVote KOEEIBDFFGE)
	{
		LCBQFQDLLEB component = this.JHDGENGBPQF.gameObject.BFCKNMFEBDM(this.QMMMEOKMMGD).GetComponent<LCBQFQDLLEB>();
		component.CLBHJLICGPC = UnityEngine.Time.time;
		component.ICFJOIPHKDJ = (float)KOEEIBDFFGE.Duration.TotalSeconds;
		component.JHDGENGBPQF = this.JHDGENGBPQF;
		component.DBPKNCDGGEP = KOEEIBDFFGE.VoteID;
		component.GDQHOCHHIJD.KJGMGPCEJJD = -91;
		component.NKKMJICKKLB.LKPOBCBOFIC(KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.ItemID).DFNQHDEDDKE());
		component.PHMFEMBPQLN.GOIHJQNMMJD = GFHGEJNHLFQ.MOGQNGEPCEO().OKBJNLOPPBF(KOEEIBDFFGE.ItemID.ToString());
		this.JHDGENGBPQF.PFEIQDIJEKE();
	}

	// Token: 0x06004607 RID: 17927 RVA: 0x0001DA9A File Offset: 0x0001BC9A
	private void IGHLFELKLJB()
	{
		IBJOGQJFQEP.HBFFCJHOCPE = this;
	}

	// Token: 0x06004608 RID: 17928 RVA: 0x0001DA9A File Offset: 0x0001BC9A
	private void LJBKGHHLMFB()
	{
		IBJOGQJFQEP.HBFFCJHOCPE = this;
	}

	// Token: 0x06004609 RID: 17929 RVA: 0x0021D848 File Offset: 0x0021BA48
	public void GDLOGGBKIGJ(Loot KOEEIBDFFGE)
	{
		if (KOEEIBDFFGE.Result == (LootVoteResult)4)
		{
			CNCJKLNHQBH.MOGQNGEPCEO().MIDPIFHNNDK("Language" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).Name + " won't go any higher!\r\n");
		}
		else if (KOEEIBDFFGE.Result == LootVoteResult.Won)
		{
			CNCJKLNHQBH.BJLGEDCPENQ().MIDPIFHNNDK("nopp" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).JQBDPHILQJO() + "item: ");
		}
		else if (KOEEIBDFFGE.Result == (LootVoteResult)7)
		{
			CNCJKLNHQBH.BJLGEDCPENQ().MIDPIFHNNDK("m_TangentMode" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).Name + "12:");
		}
		else if (KOEEIBDFFGE.Result == LootVoteResult.TimedOut)
		{
			CNCJKLNHQBH.QOQONHOOLNE.GQOBKDLOCDL("_ExposureEV" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).FLFQBGJQBBD() + " was hurt by poison!\r\n");
		}
		if (KOEEIBDFFGE.Result != LootVoteResult.Won)
		{
			CNCJKLNHQBH.QOQONHOOLNE.MIDPIFHNNDK(KOEEIBDFFGE.Winner + "[ATK]" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).DFNQHDEDDKE() + "ContextMenu");
		}
	}

	// Token: 0x0600460A RID: 17930 RVA: 0x0001DAA2 File Offset: 0x0001BCA2
	public static IBJOGQJFQEP MKMJKLDDNDD()
	{
		return IBJOGQJFQEP.HBFFCJHOCPE;
	}

	// Token: 0x0600460B RID: 17931 RVA: 0x0021D978 File Offset: 0x0021BB78
	public void QNKJOHMPQFJ(LootVote KOEEIBDFFGE)
	{
		LCBQFQDLLEB component = this.JHDGENGBPQF.gameObject.BFCKNMFEBDM(this.QMMMEOKMMGD).GetComponent<LCBQFQDLLEB>();
		component.CLBHJLICGPC = UnityEngine.Time.time;
		component.ICFJOIPHKDJ = (float)KOEEIBDFFGE.Duration.TotalSeconds;
		component.JHDGENGBPQF = this.JHDGENGBPQF;
		component.DBPKNCDGGEP = KOEEIBDFFGE.VoteID;
		component.GDQHOCHHIJD.KJGMGPCEJJD = -2;
		component.NKKMJICKKLB.PIDLOFMIEFQ = KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.ItemID).JQBDPHILQJO();
		component.PHMFEMBPQLN.GOIHJQNMMJD = GFHGEJNHLFQ.BEKHPOHIPDE().OKBJNLOPPBF(KOEEIBDFFGE.ItemID.ToString());
		this.JHDGENGBPQF.Reposition();
	}

	// Token: 0x0600460C RID: 17932 RVA: 0x0021DA38 File Offset: 0x0021BC38
	public void MHJNPEHOIGN(LootVote KOEEIBDFFGE)
	{
		LCBQFQDLLEB component = this.JHDGENGBPQF.gameObject.BFCKNMFEBDM(this.QMMMEOKMMGD).GetComponent<LCBQFQDLLEB>();
		component.CLBHJLICGPC = UnityEngine.Time.time;
		component.ICFJOIPHKDJ = (float)KOEEIBDFFGE.Duration.TotalSeconds;
		component.JHDGENGBPQF = this.JHDGENGBPQF;
		component.DBPKNCDGGEP = KOEEIBDFFGE.VoteID;
		component.GDQHOCHHIJD.KJGMGPCEJJD = -124;
		component.NKKMJICKKLB.PIDLOFMIEFQ = KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.ItemID).DFNQHDEDDKE();
		component.PHMFEMBPQLN.GOIHJQNMMJD = GFHGEJNHLFQ.QOQONHOOLNE.QDMQEBHOENL(KOEEIBDFFGE.ItemID.ToString());
		this.JHDGENGBPQF.Reposition();
	}

	// Token: 0x0600460D RID: 17933 RVA: 0x0001DA9A File Offset: 0x0001BC9A
	private void CGGDNNKBIJC()
	{
		IBJOGQJFQEP.HBFFCJHOCPE = this;
	}

	// Token: 0x0600460E RID: 17934 RVA: 0x0001DA9A File Offset: 0x0001BC9A
	private void LIPJCQHLQCQ()
	{
		IBJOGQJFQEP.HBFFCJHOCPE = this;
	}

	// Token: 0x17000292 RID: 658
	// (get) Token: 0x0600460F RID: 17935 RVA: 0x0001DAA2 File Offset: 0x0001BCA2
	public static IBJOGQJFQEP QOQONHOOLNE
	{
		get
		{
			return IBJOGQJFQEP.HBFFCJHOCPE;
		}
	}

	// Token: 0x06004610 RID: 17936 RVA: 0x0021DAF8 File Offset: 0x0021BCF8
	public void QLFMBHFNBLM(Loot KOEEIBDFFGE)
	{
		if (KOEEIBDFFGE.Result == (LootVoteResult)4)
		{
			CNCJKLNHQBH.MOGQNGEPCEO().MIDPIFHNNDK("[PG]" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).FLFQBGJQBBD() + "normal");
		}
		else if (KOEEIBDFFGE.Result == LootVoteResult.Won)
		{
			CNCJKLNHQBH.BJLGEDCPENQ().MIDPIFHNNDK("deltastream" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).JQBDPHILQJO() + "stamina");
		}
		else if (KOEEIBDFFGE.Result == LootVoteResult.Passed)
		{
			CNCJKLNHQBH.BJLGEDCPENQ().MIDPIFHNNDK("Hidden/Post FX/Builtin Debug Views" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).JQBDPHILQJO() + "[-]");
		}
		else if (KOEEIBDFFGE.Result == LootVoteResult.TimedOut)
		{
			CNCJKLNHQBH.MOGQNGEPCEO().MIDPIFHNNDK("][/pok] " + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).FLFQBGJQBBD() + "Assets/AssetBundles/MapAssets2/Model Materials/WareHouses/t105_mado_mat.mat");
		}
		if (KOEEIBDFFGE.Result != LootVoteResult.TimedOut)
		{
			CNCJKLNHQBH.QOQONHOOLNE.MIDPIFHNNDK(KOEEIBDFFGE.Winner + "sandstorm" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).Name + "-");
		}
	}

	// Token: 0x06004611 RID: 17937 RVA: 0x0001DA9A File Offset: 0x0001BC9A
	private void LBIJFCFPKNM()
	{
		IBJOGQJFQEP.HBFFCJHOCPE = this;
	}

	// Token: 0x06004612 RID: 17938 RVA: 0x0001DA9A File Offset: 0x0001BC9A
	private void FOLBFDNJLII()
	{
		IBJOGQJFQEP.HBFFCJHOCPE = this;
	}

	// Token: 0x06004613 RID: 17939 RVA: 0x0021DC28 File Offset: 0x0021BE28
	public void GBECGMFIKHH(Loot KOEEIBDFFGE)
	{
		if (KOEEIBDFFGE.Result == LootVoteResult.Passed)
		{
			CNCJKLNHQBH.MOGQNGEPCEO().MIDPIFHNNDK("Demote" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).JQBDPHILQJO() + "CombinersAlphaPassThrough");
		}
		else if (KOEEIBDFFGE.Result == LootVoteResult.Won)
		{
			CNCJKLNHQBH.BJLGEDCPENQ().MIDPIFHNNDK("toxicboost" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).JQBDPHILQJO() + "2D");
		}
		else if (KOEEIBDFFGE.Result == (LootVoteResult)5)
		{
			CNCJKLNHQBH.QOQONHOOLNE.MIDPIFHNNDK("[ffff00]" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).Name + " go!\r\n");
		}
		else if (KOEEIBDFFGE.Result == LootVoteResult.TimedOut)
		{
			CNCJKLNHQBH.QOQONHOOLNE.MIDPIFHNNDK("(H)" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).DFNQHDEDDKE() + "_MainTex");
		}
		if (KOEEIBDFFGE.Result != LootVoteResult.Won)
		{
			CNCJKLNHQBH.BJLGEDCPENQ().MIDPIFHNNDK(KOEEIBDFFGE.Winner + "Shop" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).DFNQHDEDDKE() + "Assets/AssetBundles/MapAssets/Model Materials/ShortCut_Window.mat");
		}
	}

	// Token: 0x06004614 RID: 17940 RVA: 0x0001DA9A File Offset: 0x0001BC9A
	private void Awake()
	{
		IBJOGQJFQEP.HBFFCJHOCPE = this;
	}

	// Token: 0x06004615 RID: 17941 RVA: 0x0001DA9A File Offset: 0x0001BC9A
	private void OHNCEMNBBPF()
	{
		IBJOGQJFQEP.HBFFCJHOCPE = this;
	}

	// Token: 0x06004616 RID: 17942 RVA: 0x0021DD58 File Offset: 0x0021BF58
	public void KPFOIFONCNB(LootVote KOEEIBDFFGE)
	{
		LCBQFQDLLEB component = this.JHDGENGBPQF.gameObject.BFCKNMFEBDM(this.QMMMEOKMMGD).GetComponent<LCBQFQDLLEB>();
		component.CLBHJLICGPC = UnityEngine.Time.time;
		component.ICFJOIPHKDJ = (float)KOEEIBDFFGE.Duration.TotalSeconds;
		component.JHDGENGBPQF = this.JHDGENGBPQF;
		component.DBPKNCDGGEP = KOEEIBDFFGE.VoteID;
		component.GDQHOCHHIJD.KJGMGPCEJJD = 91;
		component.NKKMJICKKLB.PIDLOFMIEFQ = KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.ItemID).FLFQBGJQBBD();
		component.PHMFEMBPQLN.GOIHJQNMMJD = GFHGEJNHLFQ.QOQONHOOLNE.PINEJNIDONB(KOEEIBDFFGE.ItemID.ToString());
		this.JHDGENGBPQF.PFEIQDIJEKE();
	}

	// Token: 0x06004617 RID: 17943 RVA: 0x0001DAA2 File Offset: 0x0001BCA2
	public static IBJOGQJFQEP GFNJCNOBMON()
	{
		return IBJOGQJFQEP.HBFFCJHOCPE;
	}

	// Token: 0x06004618 RID: 17944 RVA: 0x0021DE18 File Offset: 0x0021C018
	public void KOPGFIIJDHI(Loot KOEEIBDFFGE)
	{
		if (KOEEIBDFFGE.Result == LootVoteResult.Lost)
		{
			CNCJKLNHQBH.QOQONHOOLNE.MIDPIFHNNDK("You lost 1x " + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).Name + ".");
		}
		else if (KOEEIBDFFGE.Result == LootVoteResult.Won)
		{
			CNCJKLNHQBH.QOQONHOOLNE.MIDPIFHNNDK("You won 1x " + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).Name + ".");
		}
		else if (KOEEIBDFFGE.Result == LootVoteResult.Passed)
		{
			CNCJKLNHQBH.QOQONHOOLNE.MIDPIFHNNDK("You passed on " + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).Name + ".");
		}
		else if (KOEEIBDFFGE.Result == LootVoteResult.TimedOut)
		{
			CNCJKLNHQBH.QOQONHOOLNE.MIDPIFHNNDK("Roll timed out on " + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).Name + ".");
		}
		if (KOEEIBDFFGE.Result != LootVoteResult.Won)
		{
			CNCJKLNHQBH.QOQONHOOLNE.MIDPIFHNNDK(KOEEIBDFFGE.Winner + " won 1x " + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).Name + ".");
		}
	}

	// Token: 0x06004619 RID: 17945 RVA: 0x0021DF48 File Offset: 0x0021C148
	public void GBLFHDEKCJP(LootVote KOEEIBDFFGE)
	{
		LCBQFQDLLEB component = this.JHDGENGBPQF.gameObject.BFCKNMFEBDM(this.QMMMEOKMMGD).GetComponent<LCBQFQDLLEB>();
		component.CLBHJLICGPC = UnityEngine.Time.time;
		component.ICFJOIPHKDJ = (float)KOEEIBDFFGE.Duration.TotalSeconds;
		component.JHDGENGBPQF = this.JHDGENGBPQF;
		component.DBPKNCDGGEP = KOEEIBDFFGE.VoteID;
		component.GDQHOCHHIJD.KJGMGPCEJJD = -193;
		component.NKKMJICKKLB.LKPOBCBOFIC(KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.ItemID).NDPGCGDLEEQ());
		component.PHMFEMBPQLN.GOIHJQNMMJD = GFHGEJNHLFQ.MOGQNGEPCEO().OKBJNLOPPBF(KOEEIBDFFGE.ItemID.ToString());
		this.JHDGENGBPQF.Reposition();
	}

	// Token: 0x0600461A RID: 17946 RVA: 0x0001DA9A File Offset: 0x0001BC9A
	private void BMLEDJDBLCI()
	{
		IBJOGQJFQEP.HBFFCJHOCPE = this;
	}

	// Token: 0x0600461B RID: 17947 RVA: 0x0001DAA2 File Offset: 0x0001BCA2
	public static IBJOGQJFQEP QGICBFOILJH()
	{
		return IBJOGQJFQEP.HBFFCJHOCPE;
	}

	// Token: 0x0600461C RID: 17948 RVA: 0x0021E008 File Offset: 0x0021C208
	public void QBCNMDEQOMN(LootVote KOEEIBDFFGE)
	{
		LCBQFQDLLEB component = this.JHDGENGBPQF.gameObject.BFCKNMFEBDM(this.QMMMEOKMMGD).GetComponent<LCBQFQDLLEB>();
		component.CLBHJLICGPC = UnityEngine.Time.time;
		component.ICFJOIPHKDJ = (float)KOEEIBDFFGE.Duration.TotalSeconds;
		component.JHDGENGBPQF = this.JHDGENGBPQF;
		component.DBPKNCDGGEP = KOEEIBDFFGE.VoteID;
		component.GDQHOCHHIJD.KJGMGPCEJJD = -150;
		component.NKKMJICKKLB.LKPOBCBOFIC(KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.ItemID).FLFQBGJQBBD());
		component.PHMFEMBPQLN.GOIHJQNMMJD = GFHGEJNHLFQ.MOGQNGEPCEO().QDMQEBHOENL(KOEEIBDFFGE.ItemID.ToString());
		this.JHDGENGBPQF.Reposition();
	}

	// Token: 0x0600461D RID: 17949 RVA: 0x0021E0C8 File Offset: 0x0021C2C8
	public void BOHLHFKCDHI(LootVote KOEEIBDFFGE)
	{
		LCBQFQDLLEB component = this.JHDGENGBPQF.gameObject.BFCKNMFEBDM(this.QMMMEOKMMGD).GetComponent<LCBQFQDLLEB>();
		component.CLBHJLICGPC = UnityEngine.Time.time;
		component.ICFJOIPHKDJ = (float)KOEEIBDFFGE.Duration.TotalSeconds;
		component.JHDGENGBPQF = this.JHDGENGBPQF;
		component.DBPKNCDGGEP = KOEEIBDFFGE.VoteID;
		component.GDQHOCHHIJD.KJGMGPCEJJD = 170;
		component.NKKMJICKKLB.PIDLOFMIEFQ = KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.ItemID).NDPGCGDLEEQ();
		component.PHMFEMBPQLN.GOIHJQNMMJD = GFHGEJNHLFQ.MOGQNGEPCEO().OKBJNLOPPBF(KOEEIBDFFGE.ItemID.ToString());
		this.JHDGENGBPQF.Reposition();
	}

	// Token: 0x0600461E RID: 17950 RVA: 0x0021E188 File Offset: 0x0021C388
	public void ELJQIEOLGKE(LootVote KOEEIBDFFGE)
	{
		LCBQFQDLLEB component = this.JHDGENGBPQF.gameObject.BFCKNMFEBDM(this.QMMMEOKMMGD).GetComponent<LCBQFQDLLEB>();
		component.CLBHJLICGPC = UnityEngine.Time.time;
		component.ICFJOIPHKDJ = (float)KOEEIBDFFGE.Duration.TotalSeconds;
		component.JHDGENGBPQF = this.JHDGENGBPQF;
		component.DBPKNCDGGEP = KOEEIBDFFGE.VoteID;
		component.GDQHOCHHIJD.KJGMGPCEJJD = 49;
		component.NKKMJICKKLB.PIDLOFMIEFQ = KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.ItemID).NDPGCGDLEEQ();
		component.PHMFEMBPQLN.GOIHJQNMMJD = GFHGEJNHLFQ.GGBPGMMCGLI().QDMQEBHOENL(KOEEIBDFFGE.ItemID.ToString());
		this.JHDGENGBPQF.PFEIQDIJEKE();
	}

	// Token: 0x0600461F RID: 17951 RVA: 0x0001DAA2 File Offset: 0x0001BCA2
	public static IBJOGQJFQEP FPQNIQELKMC()
	{
		return IBJOGQJFQEP.HBFFCJHOCPE;
	}

	// Token: 0x06004620 RID: 17952 RVA: 0x0021E248 File Offset: 0x0021C448
	public void OLLODFLPEOH(LootVote KOEEIBDFFGE)
	{
		LCBQFQDLLEB component = this.JHDGENGBPQF.gameObject.BFCKNMFEBDM(this.QMMMEOKMMGD).GetComponent<LCBQFQDLLEB>();
		component.CLBHJLICGPC = UnityEngine.Time.time;
		component.ICFJOIPHKDJ = (float)KOEEIBDFFGE.Duration.TotalSeconds;
		component.JHDGENGBPQF = this.JHDGENGBPQF;
		component.DBPKNCDGGEP = KOEEIBDFFGE.VoteID;
		component.GDQHOCHHIJD.KJGMGPCEJJD = -102;
		component.NKKMJICKKLB.LKPOBCBOFIC(KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.ItemID).JQBDPHILQJO());
		component.PHMFEMBPQLN.GOIHJQNMMJD = GFHGEJNHLFQ.MOGQNGEPCEO().QDMQEBHOENL(KOEEIBDFFGE.ItemID.ToString());
		this.JHDGENGBPQF.Reposition();
	}

	// Token: 0x06004621 RID: 17953 RVA: 0x0001DAA2 File Offset: 0x0001BCA2
	public static IBJOGQJFQEP PEHMQLLDODG()
	{
		return IBJOGQJFQEP.HBFFCJHOCPE;
	}

	// Token: 0x06004622 RID: 17954 RVA: 0x0021E308 File Offset: 0x0021C508
	public void HILBPHGNJPQ(Loot KOEEIBDFFGE)
	{
		if (KOEEIBDFFGE.Result == LootVoteResult.Passed)
		{
			CNCJKLNHQBH.QOQONHOOLNE.GQOBKDLOCDL("Pokeball_Break" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).Name + "trace");
		}
		else if (KOEEIBDFFGE.Result == LootVoteResult.Won)
		{
			CNCJKLNHQBH.MOGQNGEPCEO().MIDPIFHNNDK("!\r\n" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).Name + "Icon_Pokemon_Alive");
		}
		else if (KOEEIBDFFGE.Result == (LootVoteResult)4)
		{
			CNCJKLNHQBH.BJLGEDCPENQ().GQOBKDLOCDL("-at" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).Name + "pressure");
		}
		else if (KOEEIBDFFGE.Result == LootVoteResult.TimedOut)
		{
			CNCJKLNHQBH.QOQONHOOLNE.MIDPIFHNNDK("\n" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).DFNQHDEDDKE() + "Surf");
		}
		if (KOEEIBDFFGE.Result != LootVoteResult.TimedOut)
		{
			CNCJKLNHQBH.MOGQNGEPCEO().MIDPIFHNNDK(KOEEIBDFFGE.Winner + "dispMode" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).DFNQHDEDDKE() + "Ditto");
		}
	}

	// Token: 0x06004623 RID: 17955 RVA: 0x0001DA9A File Offset: 0x0001BC9A
	private void PKMPEFHBDEE()
	{
		IBJOGQJFQEP.HBFFCJHOCPE = this;
	}

	// Token: 0x06004624 RID: 17956 RVA: 0x0021E438 File Offset: 0x0021C638
	public void DHFJIDLDBJF(LootVote KOEEIBDFFGE)
	{
		LCBQFQDLLEB component = this.JHDGENGBPQF.gameObject.BFCKNMFEBDM(this.QMMMEOKMMGD).GetComponent<LCBQFQDLLEB>();
		component.CLBHJLICGPC = UnityEngine.Time.time;
		component.ICFJOIPHKDJ = (float)KOEEIBDFFGE.Duration.TotalSeconds;
		component.JHDGENGBPQF = this.JHDGENGBPQF;
		component.DBPKNCDGGEP = KOEEIBDFFGE.VoteID;
		component.GDQHOCHHIJD.KJGMGPCEJJD = 60;
		component.NKKMJICKKLB.LKPOBCBOFIC(KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.ItemID).JQBDPHILQJO());
		component.PHMFEMBPQLN.GOIHJQNMMJD = GFHGEJNHLFQ.GGBPGMMCGLI().QDMQEBHOENL(KOEEIBDFFGE.ItemID.ToString());
		this.JHDGENGBPQF.PFEIQDIJEKE();
	}

	// Token: 0x06004625 RID: 17957 RVA: 0x0001DAA2 File Offset: 0x0001BCA2
	public static IBJOGQJFQEP JJIGBQBELCM()
	{
		return IBJOGQJFQEP.HBFFCJHOCPE;
	}

	// Token: 0x06004626 RID: 17958 RVA: 0x0001DAA2 File Offset: 0x0001BCA2
	public static IBJOGQJFQEP PFQBLOEPBJB()
	{
		return IBJOGQJFQEP.HBFFCJHOCPE;
	}

	// Token: 0x06004627 RID: 17959 RVA: 0x0021E4F8 File Offset: 0x0021C6F8
	public void BIPHODJKQDM(Loot KOEEIBDFFGE)
	{
		if (KOEEIBDFFGE.Result == (LootVoteResult)6)
		{
			CNCJKLNHQBH.MOGQNGEPCEO().GQOBKDLOCDL("cursedbody" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).Name + "???");
		}
		else if (KOEEIBDFFGE.Result == LootVoteResult.TimedOut)
		{
			CNCJKLNHQBH.MOGQNGEPCEO().MIDPIFHNNDK("FOG_EXP" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).NDPGCGDLEEQ() + " is hoping to take its attacker down with it!\r\n");
		}
		else if (KOEEIBDFFGE.Result == (LootVoteResult)6)
		{
			CNCJKLNHQBH.QOQONHOOLNE.MIDPIFHNNDK("settag(" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).FLFQBGJQBBD() + "r");
		}
		else if (KOEEIBDFFGE.Result == LootVoteResult.TimedOut)
		{
			CNCJKLNHQBH.BJLGEDCPENQ().MIDPIFHNNDK("VolumetricFogAndMist/Chaos Lerp" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).DFNQHDEDDKE() + "Assets/AssetBundles/Crys/");
		}
		if (KOEEIBDFFGE.Result != LootVoteResult.Won)
		{
			CNCJKLNHQBH.QOQONHOOLNE.GQOBKDLOCDL(KOEEIBDFFGE.Winner + "[PG]" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).JQBDPHILQJO() + "Player/Hair");
		}
	}

	// Token: 0x06004628 RID: 17960 RVA: 0x0001DA9A File Offset: 0x0001BC9A
	private void DCBCOLQOKKB()
	{
		IBJOGQJFQEP.HBFFCJHOCPE = this;
	}

	// Token: 0x06004629 RID: 17961 RVA: 0x0001DA9A File Offset: 0x0001BC9A
	private void IHGDMCFDINH()
	{
		IBJOGQJFQEP.HBFFCJHOCPE = this;
	}

	// Token: 0x0600462A RID: 17962 RVA: 0x0001DAA2 File Offset: 0x0001BCA2
	public static IBJOGQJFQEP OQDOKBJNBBL()
	{
		return IBJOGQJFQEP.HBFFCJHOCPE;
	}

	// Token: 0x0600462B RID: 17963 RVA: 0x0021E628 File Offset: 0x0021C828
	public void KCPCKMEMFDB(LootVote KOEEIBDFFGE)
	{
		LCBQFQDLLEB component = this.JHDGENGBPQF.gameObject.BFCKNMFEBDM(this.QMMMEOKMMGD).GetComponent<LCBQFQDLLEB>();
		component.CLBHJLICGPC = UnityEngine.Time.time;
		component.ICFJOIPHKDJ = (float)KOEEIBDFFGE.Duration.TotalSeconds;
		component.JHDGENGBPQF = this.JHDGENGBPQF;
		component.DBPKNCDGGEP = KOEEIBDFFGE.VoteID;
		component.GDQHOCHHIJD.KJGMGPCEJJD = 140;
		component.NKKMJICKKLB.PIDLOFMIEFQ = KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.ItemID).Name;
		component.PHMFEMBPQLN.GOIHJQNMMJD = GFHGEJNHLFQ.QOQONHOOLNE.QDMQEBHOENL(KOEEIBDFFGE.ItemID.ToString());
		this.JHDGENGBPQF.Reposition();
	}

	// Token: 0x0600462C RID: 17964 RVA: 0x0001DAA2 File Offset: 0x0001BCA2
	public static IBJOGQJFQEP LIOKMNJHQCD()
	{
		return IBJOGQJFQEP.HBFFCJHOCPE;
	}

	// Token: 0x0600462D RID: 17965 RVA: 0x0001DAA2 File Offset: 0x0001BCA2
	public static IBJOGQJFQEP MFQIJCPBPDF()
	{
		return IBJOGQJFQEP.HBFFCJHOCPE;
	}

	// Token: 0x0600462E RID: 17966 RVA: 0x0001DAA2 File Offset: 0x0001BCA2
	public static IBJOGQJFQEP HGEKKNEPOHK()
	{
		return IBJOGQJFQEP.HBFFCJHOCPE;
	}

	// Token: 0x0600462F RID: 17967 RVA: 0x0021E6E8 File Offset: 0x0021C8E8
	public void MHBBKMDGFMB(Loot KOEEIBDFFGE)
	{
		if (KOEEIBDFFGE.Result == (LootVoteResult)5)
		{
			CNCJKLNHQBH.MOGQNGEPCEO().MIDPIFHNNDK("'s [ffff00]" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).DFNQHDEDDKE() + "_BlendPower");
		}
		else if (KOEEIBDFFGE.Result == LootVoteResult.TimedOut)
		{
			CNCJKLNHQBH.MOGQNGEPCEO().GQOBKDLOCDL("More Likely Female Encounters" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).NDPGCGDLEEQ() + "[00FF00]");
		}
		else if (KOEEIBDFFGE.Result == (LootVoteResult)4)
		{
			CNCJKLNHQBH.BJLGEDCPENQ().GQOBKDLOCDL("endure" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).DFNQHDEDDKE() + "Assets/AssetBundles/MapAssets/Models/Materials/chip_mado.mat");
		}
		else if (KOEEIBDFFGE.Result == LootVoteResult.TimedOut)
		{
			CNCJKLNHQBH.MOGQNGEPCEO().GQOBKDLOCDL("Unlit/Transparent Colored" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).NDPGCGDLEEQ() + "Chance for same Nature");
		}
		if (KOEEIBDFFGE.Result != LootVoteResult.Won)
		{
			CNCJKLNHQBH.MOGQNGEPCEO().MIDPIFHNNDK(KOEEIBDFFGE.Winner + "It started to rain!" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).FLFQBGJQBBD() + "pacman");
		}
	}

	// Token: 0x06004630 RID: 17968 RVA: 0x0001DAA2 File Offset: 0x0001BCA2
	public static IBJOGQJFQEP KGOPJQOMMNC()
	{
		return IBJOGQJFQEP.HBFFCJHOCPE;
	}

	// Token: 0x06004631 RID: 17969 RVA: 0x0001DA9A File Offset: 0x0001BC9A
	private void OJJILLOOFKF()
	{
		IBJOGQJFQEP.HBFFCJHOCPE = this;
	}

	// Token: 0x06004632 RID: 17970 RVA: 0x0001DAA2 File Offset: 0x0001BCA2
	public static IBJOGQJFQEP PDPCLOECLOF()
	{
		return IBJOGQJFQEP.HBFFCJHOCPE;
	}

	// Token: 0x06004633 RID: 17971 RVA: 0x0021E818 File Offset: 0x0021CA18
	public void PPMQDPCBBJM(LootVote KOEEIBDFFGE)
	{
		LCBQFQDLLEB component = this.JHDGENGBPQF.gameObject.BFCKNMFEBDM(this.QMMMEOKMMGD).GetComponent<LCBQFQDLLEB>();
		component.CLBHJLICGPC = UnityEngine.Time.time;
		component.ICFJOIPHKDJ = (float)KOEEIBDFFGE.Duration.TotalSeconds;
		component.JHDGENGBPQF = this.JHDGENGBPQF;
		component.DBPKNCDGGEP = KOEEIBDFFGE.VoteID;
		component.GDQHOCHHIJD.KJGMGPCEJJD = 1;
		component.NKKMJICKKLB.PIDLOFMIEFQ = KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.ItemID).FLFQBGJQBBD();
		component.PHMFEMBPQLN.GOIHJQNMMJD = GFHGEJNHLFQ.GGBPGMMCGLI().PINEJNIDONB(KOEEIBDFFGE.ItemID.ToString());
		this.JHDGENGBPQF.Reposition();
	}

	// Token: 0x06004634 RID: 17972 RVA: 0x0001DA9A File Offset: 0x0001BC9A
	private void PCHJHFGCOCK()
	{
		IBJOGQJFQEP.HBFFCJHOCPE = this;
	}

	// Token: 0x06004635 RID: 17973 RVA: 0x0021E8D8 File Offset: 0x0021CAD8
	public void HFPDPDDPEJK(LootVote KOEEIBDFFGE)
	{
		LCBQFQDLLEB component = this.JHDGENGBPQF.gameObject.BFCKNMFEBDM(this.QMMMEOKMMGD).GetComponent<LCBQFQDLLEB>();
		component.CLBHJLICGPC = UnityEngine.Time.time;
		component.ICFJOIPHKDJ = (float)KOEEIBDFFGE.Duration.TotalSeconds;
		component.JHDGENGBPQF = this.JHDGENGBPQF;
		component.DBPKNCDGGEP = KOEEIBDFFGE.VoteID;
		component.GDQHOCHHIJD.KJGMGPCEJJD = 5;
		component.NKKMJICKKLB.PIDLOFMIEFQ = KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.ItemID).Name;
		component.PHMFEMBPQLN.GOIHJQNMMJD = GFHGEJNHLFQ.MOGQNGEPCEO().QDMQEBHOENL(KOEEIBDFFGE.ItemID.ToString());
		this.JHDGENGBPQF.PFEIQDIJEKE();
	}

	// Token: 0x06004636 RID: 17974 RVA: 0x0021E998 File Offset: 0x0021CB98
	public void QJINGGOBOPF(Loot KOEEIBDFFGE)
	{
		if (KOEEIBDFFGE.Result == LootVoteResult.Won)
		{
			CNCJKLNHQBH.BJLGEDCPENQ().MIDPIFHNNDK("P. " + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).DFNQHDEDDKE() + "Blank");
		}
		else if (KOEEIBDFFGE.Result == LootVoteResult.Won)
		{
			CNCJKLNHQBH.MOGQNGEPCEO().GQOBKDLOCDL("#,##0" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).FLFQBGJQBBD() + "14");
		}
		else if (KOEEIBDFFGE.Result == (LootVoteResult)5)
		{
			CNCJKLNHQBH.MOGQNGEPCEO().MIDPIFHNNDK(" can't use items anymore!\r\n" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).JQBDPHILQJO() + "Boundaries Trigger");
		}
		else if (KOEEIBDFFGE.Result == LootVoteResult.TimedOut)
		{
			CNCJKLNHQBH.MOGQNGEPCEO().MIDPIFHNNDK("blaze" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).FLFQBGJQBBD() + "[00DD00]Owned");
		}
		if (KOEEIBDFFGE.Result != LootVoteResult.Won)
		{
			CNCJKLNHQBH.BJLGEDCPENQ().MIDPIFHNNDK(KOEEIBDFFGE.Winner + " @ " + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).FLFQBGJQBBD() + "](");
		}
	}

	// Token: 0x06004638 RID: 17976 RVA: 0x0021EAC8 File Offset: 0x0021CCC8
	public void LOFOGKFCICL(LootVote KOEEIBDFFGE)
	{
		LCBQFQDLLEB component = this.JHDGENGBPQF.gameObject.BFCKNMFEBDM(this.QMMMEOKMMGD).GetComponent<LCBQFQDLLEB>();
		component.CLBHJLICGPC = UnityEngine.Time.time;
		component.ICFJOIPHKDJ = (float)KOEEIBDFFGE.Duration.TotalSeconds;
		component.JHDGENGBPQF = this.JHDGENGBPQF;
		component.DBPKNCDGGEP = KOEEIBDFFGE.VoteID;
		component.GDQHOCHHIJD.KJGMGPCEJJD = 22;
		component.NKKMJICKKLB.LKPOBCBOFIC(KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.ItemID).JQBDPHILQJO());
		component.PHMFEMBPQLN.GOIHJQNMMJD = GFHGEJNHLFQ.BEKHPOHIPDE().QDMQEBHOENL(KOEEIBDFFGE.ItemID.ToString());
		this.JHDGENGBPQF.PFEIQDIJEKE();
	}

	// Token: 0x06004639 RID: 17977 RVA: 0x0021EB88 File Offset: 0x0021CD88
	public void BCQJHNGLEEF(LootVote KOEEIBDFFGE)
	{
		LCBQFQDLLEB component = this.JHDGENGBPQF.gameObject.BFCKNMFEBDM(this.QMMMEOKMMGD).GetComponent<LCBQFQDLLEB>();
		component.CLBHJLICGPC = UnityEngine.Time.time;
		component.ICFJOIPHKDJ = (float)KOEEIBDFFGE.Duration.TotalSeconds;
		component.JHDGENGBPQF = this.JHDGENGBPQF;
		component.DBPKNCDGGEP = KOEEIBDFFGE.VoteID;
		component.GDQHOCHHIJD.KJGMGPCEJJD = 133;
		component.NKKMJICKKLB.LKPOBCBOFIC(KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.ItemID).Name);
		component.PHMFEMBPQLN.GOIHJQNMMJD = GFHGEJNHLFQ.BEKHPOHIPDE().PINEJNIDONB(KOEEIBDFFGE.ItemID.ToString());
		this.JHDGENGBPQF.PFEIQDIJEKE();
	}

	// Token: 0x0600463A RID: 17978 RVA: 0x0001DA9A File Offset: 0x0001BC9A
	private void OHHFMNHJEOJ()
	{
		IBJOGQJFQEP.HBFFCJHOCPE = this;
	}

	// Token: 0x0600463B RID: 17979 RVA: 0x0021EC48 File Offset: 0x0021CE48
	public void CPLNQLKMJHP(Loot KOEEIBDFFGE)
	{
		if (KOEEIBDFFGE.Result == LootVoteResult.Won)
		{
			CNCJKLNHQBH.BJLGEDCPENQ().MIDPIFHNNDK("MSGBOX - " + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).JQBDPHILQJO() + "_AutoExposure");
		}
		else if (KOEEIBDFFGE.Result == LootVoteResult.Won)
		{
			CNCJKLNHQBH.BJLGEDCPENQ().MIDPIFHNNDK("HidePanel" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).FLFQBGJQBBD() + "Up");
		}
		else if (KOEEIBDFFGE.Result == (LootVoteResult)4)
		{
			CNCJKLNHQBH.BJLGEDCPENQ().MIDPIFHNNDK("K" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).FLFQBGJQBBD() + "ACC: -");
		}
		else if (KOEEIBDFFGE.Result == LootVoteResult.TimedOut)
		{
			CNCJKLNHQBH.MOGQNGEPCEO().GQOBKDLOCDL(" (TextureClip)" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).Name + "(C)");
		}
		if (KOEEIBDFFGE.Result != LootVoteResult.TimedOut)
		{
			CNCJKLNHQBH.MOGQNGEPCEO().MIDPIFHNNDK(KOEEIBDFFGE.Winner + "Hidden/Post FX/Lut Generator" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).NDPGCGDLEEQ() + "The bursting flame hit ");
		}
	}

	// Token: 0x0600463C RID: 17980 RVA: 0x0021ED78 File Offset: 0x0021CF78
	public void NQHIEGLDQGE(LootVote KOEEIBDFFGE)
	{
		LCBQFQDLLEB component = this.JHDGENGBPQF.gameObject.BFCKNMFEBDM(this.QMMMEOKMMGD).GetComponent<LCBQFQDLLEB>();
		component.CLBHJLICGPC = UnityEngine.Time.time;
		component.ICFJOIPHKDJ = (float)KOEEIBDFFGE.Duration.TotalSeconds;
		component.JHDGENGBPQF = this.JHDGENGBPQF;
		component.DBPKNCDGGEP = KOEEIBDFFGE.VoteID;
		component.GDQHOCHHIJD.KJGMGPCEJJD = -70;
		component.NKKMJICKKLB.PIDLOFMIEFQ = KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.ItemID).Name;
		component.PHMFEMBPQLN.GOIHJQNMMJD = GFHGEJNHLFQ.QOQONHOOLNE.QDMQEBHOENL(KOEEIBDFFGE.ItemID.ToString());
		this.JHDGENGBPQF.Reposition();
	}

	// Token: 0x0600463D RID: 17981 RVA: 0x0021EE38 File Offset: 0x0021D038
	public void GDGJNJFPEGH(LootVote KOEEIBDFFGE)
	{
		LCBQFQDLLEB component = this.JHDGENGBPQF.gameObject.BFCKNMFEBDM(this.QMMMEOKMMGD).GetComponent<LCBQFQDLLEB>();
		component.CLBHJLICGPC = UnityEngine.Time.time;
		component.ICFJOIPHKDJ = (float)KOEEIBDFFGE.Duration.TotalSeconds;
		component.JHDGENGBPQF = this.JHDGENGBPQF;
		component.DBPKNCDGGEP = KOEEIBDFFGE.VoteID;
		component.GDQHOCHHIJD.KJGMGPCEJJD = -50;
		component.NKKMJICKKLB.PIDLOFMIEFQ = KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.ItemID).FLFQBGJQBBD();
		component.PHMFEMBPQLN.GOIHJQNMMJD = GFHGEJNHLFQ.BEKHPOHIPDE().OKBJNLOPPBF(KOEEIBDFFGE.ItemID.ToString());
		this.JHDGENGBPQF.PFEIQDIJEKE();
	}

	// Token: 0x0600463E RID: 17982 RVA: 0x0021EEF8 File Offset: 0x0021D0F8
	public void MNMPPNGQHBM(LootVote KOEEIBDFFGE)
	{
		LCBQFQDLLEB component = this.JHDGENGBPQF.gameObject.BFCKNMFEBDM(this.QMMMEOKMMGD).GetComponent<LCBQFQDLLEB>();
		component.CLBHJLICGPC = UnityEngine.Time.time;
		component.ICFJOIPHKDJ = (float)KOEEIBDFFGE.Duration.TotalSeconds;
		component.JHDGENGBPQF = this.JHDGENGBPQF;
		component.DBPKNCDGGEP = KOEEIBDFFGE.VoteID;
		component.GDQHOCHHIJD.KJGMGPCEJJD = -118;
		component.NKKMJICKKLB.LKPOBCBOFIC(KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.ItemID).Name);
		component.PHMFEMBPQLN.GOIHJQNMMJD = GFHGEJNHLFQ.GGBPGMMCGLI().PINEJNIDONB(KOEEIBDFFGE.ItemID.ToString());
		this.JHDGENGBPQF.Reposition();
	}

	// Token: 0x0600463F RID: 17983 RVA: 0x0021EFB8 File Offset: 0x0021D1B8
	public void JECGDQQEDBN(LootVote KOEEIBDFFGE)
	{
		LCBQFQDLLEB component = this.JHDGENGBPQF.gameObject.BFCKNMFEBDM(this.QMMMEOKMMGD).GetComponent<LCBQFQDLLEB>();
		component.CLBHJLICGPC = UnityEngine.Time.time;
		component.ICFJOIPHKDJ = (float)KOEEIBDFFGE.Duration.TotalSeconds;
		component.JHDGENGBPQF = this.JHDGENGBPQF;
		component.DBPKNCDGGEP = KOEEIBDFFGE.VoteID;
		component.GDQHOCHHIJD.KJGMGPCEJJD = 63;
		component.NKKMJICKKLB.LKPOBCBOFIC(KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.ItemID).DFNQHDEDDKE());
		component.PHMFEMBPQLN.GOIHJQNMMJD = GFHGEJNHLFQ.BEKHPOHIPDE().OKBJNLOPPBF(KOEEIBDFFGE.ItemID.ToString());
		this.JHDGENGBPQF.Reposition();
	}

	// Token: 0x06004640 RID: 17984 RVA: 0x0001DAA2 File Offset: 0x0001BCA2
	public static IBJOGQJFQEP BCQGHQGLLPF()
	{
		return IBJOGQJFQEP.HBFFCJHOCPE;
	}

	// Token: 0x06004641 RID: 17985 RVA: 0x0001DA9A File Offset: 0x0001BC9A
	private void GJJFGJKJFCC()
	{
		IBJOGQJFQEP.HBFFCJHOCPE = this;
	}

	// Token: 0x06004642 RID: 17986 RVA: 0x0021F078 File Offset: 0x0021D278
	public void FFKQJFBNPLO(Loot KOEEIBDFFGE)
	{
		if (KOEEIBDFFGE.Result == (LootVoteResult)5)
		{
			CNCJKLNHQBH.QOQONHOOLNE.MIDPIFHNNDK("Hidden/Post FX/Temporal Anti-aliasing" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).FLFQBGJQBBD() + "The Pokémon is suffering from insomnia and cannot fall asleep.");
		}
		else if (KOEEIBDFFGE.Result == LootVoteResult.TimedOut)
		{
			CNCJKLNHQBH.BJLGEDCPENQ().GQOBKDLOCDL("FOG_POINT_LIGHT" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).FLFQBGJQBBD() + "[00DD00]Equipped");
		}
		else if (KOEEIBDFFGE.Result == (LootVoteResult)5)
		{
			CNCJKLNHQBH.MOGQNGEPCEO().MIDPIFHNNDK("CombinersColor" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).NDPGCGDLEEQ() + " surrounds itself with a protective mist!\r\n");
		}
		else if (KOEEIBDFFGE.Result == LootVoteResult.TimedOut)
		{
			CNCJKLNHQBH.MOGQNGEPCEO().MIDPIFHNNDK(", input focus" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).DFNQHDEDDKE() + "poisonpoint");
		}
		if (KOEEIBDFFGE.Result != LootVoteResult.Won)
		{
			CNCJKLNHQBH.QOQONHOOLNE.GQOBKDLOCDL(KOEEIBDFFGE.Winner + "_DestortionAmplitude" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).JQBDPHILQJO() + "[PG]");
		}
	}

	// Token: 0x06004643 RID: 17987 RVA: 0x0021F1A8 File Offset: 0x0021D3A8
	public void EGELPJCKNGJ(Loot KOEEIBDFFGE)
	{
		if (KOEEIBDFFGE.Result == LootVoteResult.TimedOut)
		{
			CNCJKLNHQBH.QOQONHOOLNE.GQOBKDLOCDL("UpS" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).NDPGCGDLEEQ() + "ability");
		}
		else if (KOEEIBDFFGE.Result == LootVoteResult.TimedOut)
		{
			CNCJKLNHQBH.BJLGEDCPENQ().GQOBKDLOCDL("Super Repel" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).JQBDPHILQJO() + "variation");
		}
		else if (KOEEIBDFFGE.Result == (LootVoteResult)5)
		{
			CNCJKLNHQBH.BJLGEDCPENQ().GQOBKDLOCDL("auroraveil" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).JQBDPHILQJO() + "Heavy Ball");
		}
		else if (KOEEIBDFFGE.Result == LootVoteResult.TimedOut)
		{
			CNCJKLNHQBH.BJLGEDCPENQ().MIDPIFHNNDK("h:mm tt" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).DFNQHDEDDKE() + "[-]\n\n");
		}
		if (KOEEIBDFFGE.Result != LootVoteResult.TimedOut)
		{
			CNCJKLNHQBH.BJLGEDCPENQ().GQOBKDLOCDL(KOEEIBDFFGE.Winner + "_Start" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).JQBDPHILQJO() + "--run");
		}
	}

	// Token: 0x06004644 RID: 17988 RVA: 0x0001DA9A File Offset: 0x0001BC9A
	private void NPEJDHMIFDJ()
	{
		IBJOGQJFQEP.HBFFCJHOCPE = this;
	}

	// Token: 0x06004645 RID: 17989 RVA: 0x0001DA9A File Offset: 0x0001BC9A
	private void IFNFKJQIBLJ()
	{
		IBJOGQJFQEP.HBFFCJHOCPE = this;
	}

	// Token: 0x06004646 RID: 17990 RVA: 0x0001DA9A File Offset: 0x0001BC9A
	private void JENKEGOEEHO()
	{
		IBJOGQJFQEP.HBFFCJHOCPE = this;
	}

	// Token: 0x06004647 RID: 17991 RVA: 0x0001DAA2 File Offset: 0x0001BCA2
	public static IBJOGQJFQEP DJMGOBBECCK()
	{
		return IBJOGQJFQEP.HBFFCJHOCPE;
	}

	// Token: 0x06004648 RID: 17992 RVA: 0x0001DAA2 File Offset: 0x0001BCA2
	public static IBJOGQJFQEP IECKOKEPENM()
	{
		return IBJOGQJFQEP.HBFFCJHOCPE;
	}

	// Token: 0x06004649 RID: 17993 RVA: 0x0001DAA2 File Offset: 0x0001BCA2
	public static IBJOGQJFQEP CKQHNOIQNQJ()
	{
		return IBJOGQJFQEP.HBFFCJHOCPE;
	}

	// Token: 0x0600464A RID: 17994 RVA: 0x0001DA9A File Offset: 0x0001BC9A
	private void EOKKQCMPDCJ()
	{
		IBJOGQJFQEP.HBFFCJHOCPE = this;
	}

	// Token: 0x0600464B RID: 17995 RVA: 0x0001DAA2 File Offset: 0x0001BCA2
	public static IBJOGQJFQEP GPMJDKJFHMH()
	{
		return IBJOGQJFQEP.HBFFCJHOCPE;
	}

	// Token: 0x0600464C RID: 17996 RVA: 0x0021F2D8 File Offset: 0x0021D4D8
	public void LLCNBHPDCCQ(Loot KOEEIBDFFGE)
	{
		if (KOEEIBDFFGE.Result == (LootVoteResult)5)
		{
			CNCJKLNHQBH.QOQONHOOLNE.MIDPIFHNNDK("Normal-type moves become Fairy-type moves. The power of those moves is boosted a little." + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).Name + "[PD]");
		}
		else if (KOEEIBDFFGE.Result == LootVoteResult.Won)
		{
			CNCJKLNHQBH.BJLGEDCPENQ().GQOBKDLOCDL("Cacophony" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).FLFQBGJQBBD() + " took the ");
		}
		else if (KOEEIBDFFGE.Result == LootVoteResult.TimedOut)
		{
			CNCJKLNHQBH.QOQONHOOLNE.GQOBKDLOCDL("Turboblaze" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).JQBDPHILQJO() + "Player/Hats/");
		}
		else if (KOEEIBDFFGE.Result == LootVoteResult.TimedOut)
		{
			CNCJKLNHQBH.BJLGEDCPENQ().GQOBKDLOCDL("HideEmote" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).DFNQHDEDDKE() + "last online ");
		}
		if (KOEEIBDFFGE.Result != LootVoteResult.Won)
		{
			CNCJKLNHQBH.MOGQNGEPCEO().GQOBKDLOCDL(KOEEIBDFFGE.Winner + "Moderator" + KGQECFKLKOP.BFNBQBMJHFL(KOEEIBDFFGE.Vote.ItemID).Name + "Applying a new Guild Logo will cost [PG]300.\n\nAre you sure you want to do this?\nInappropriate images drawn will result in account termination.");
		}
	}

	// Token: 0x0600464D RID: 17997 RVA: 0x0001DA9A File Offset: 0x0001BC9A
	private void DCJQFJOICGQ()
	{
		IBJOGQJFQEP.HBFFCJHOCPE = this;
	}

	// Token: 0x04000EF1 RID: 3825
	private static IBJOGQJFQEP HBFFCJHOCPE;

	// Token: 0x04000EF2 RID: 3826
	public BHLIGEGNFHG JHDGENGBPQF;

	// Token: 0x04000EF3 RID: 3827
	public GameObject QMMMEOKMMGD;
}
