using System;
using UnityEngine;

// Token: 0x0200006C RID: 108
[AddComponentMenu("NGUI/Interaction/Play Sound")]
public class KGJGOEICIJE : MonoBehaviour
{
	// Token: 0x06000E75 RID: 3701 RVA: 0x00073DE8 File Offset: 0x00071FE8
	private void QCEKMLKNKHP(bool IFFGDNBQHLO)
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnClick)
		{
			if (this.FIBJMBNNPBQ == IFFGDNBQHLO)
			{
				return;
			}
			this.FIBJMBNNPBQ = IFFGDNBQHLO;
		}
		if (this.EDJDMEEHDLM() && ((IFFGDNBQHLO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnMouseOver) || (!IFFGDNBQHLO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnClick)))
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000E76 RID: 3702 RVA: 0x00008CA4 File Offset: 0x00006EA4
	private void OQOKEHJOCDK()
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnClick)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000E77 RID: 3703 RVA: 0x00008CC7 File Offset: 0x00006EC7
	private void INFMNHJJDCD()
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnRelease)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000E78 RID: 3704 RVA: 0x00073E48 File Offset: 0x00072048
	private bool DMNFEHMKIQC()
	{
		if (!base.enabled)
		{
			return false;
		}
		CFDMNELIJLO component = base.GetComponent<CFDMNELIJLO>();
		return !(component == null) && component.GGBPLMICFHN;
	}

	// Token: 0x06000E79 RID: 3705 RVA: 0x00008CEA File Offset: 0x00006EEA
	private void JHQCMGKJCCI()
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnMouseOver)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000E7B RID: 3707 RVA: 0x00008CC7 File Offset: 0x00006EC7
	private void KBJOKEMFQFN()
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnRelease)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000E7C RID: 3708 RVA: 0x00008D2B File Offset: 0x00006F2B
	private void OnEnable()
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnEnable)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000E7D RID: 3709 RVA: 0x00008CEA File Offset: 0x00006EEA
	private void IFBFCHOMCEO()
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnMouseOver)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000E7E RID: 3710 RVA: 0x00073E78 File Offset: 0x00072078
	private bool JGHBGBGNHLJ()
	{
		if (!base.enabled)
		{
			return false;
		}
		CFDMNELIJLO component = base.GetComponent<CFDMNELIJLO>();
		return !(component == null) && component.EFBQLPLOMQB();
	}

	// Token: 0x06000E7F RID: 3711 RVA: 0x00073EA8 File Offset: 0x000720A8
	private void OnPress(bool FJOEKDCLKIO)
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnPress)
		{
			if (this.FIBJMBNNPBQ == FJOEKDCLKIO)
			{
				return;
			}
			this.FIBJMBNNPBQ = FJOEKDCLKIO;
		}
		if (this.BJFCGLCQLCG && ((FJOEKDCLKIO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnPress) || (!FJOEKDCLKIO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnRelease)))
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000E80 RID: 3712 RVA: 0x00073F08 File Offset: 0x00072108
	private void NQEJNHQNFLJ(bool FJOEKDCLKIO)
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnMouseOver)
		{
			if (this.FIBJMBNNPBQ == FJOEKDCLKIO)
			{
				return;
			}
			this.FIBJMBNNPBQ = FJOEKDCLKIO;
		}
		if (this.FMNMCPLDMKE() && ((FJOEKDCLKIO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnEnable) || (!FJOEKDCLKIO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.Custom)))
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000E81 RID: 3713 RVA: 0x00073F68 File Offset: 0x00072168
	private bool PPOBGMJPDKN()
	{
		if (!base.enabled)
		{
			return true;
		}
		CFDMNELIJLO component = base.GetComponent<CFDMNELIJLO>();
		return component == null || component.GGBPLMICFHN;
	}

	// Token: 0x06000E82 RID: 3714 RVA: 0x00008CEA File Offset: 0x00006EEA
	private void NDEEQCCOOEE()
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnMouseOver)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000E83 RID: 3715 RVA: 0x00008CEA File Offset: 0x00006EEA
	private void CPJJKJLFOEN()
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnMouseOver)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000E84 RID: 3716 RVA: 0x00008D4E File Offset: 0x00006F4E
	private void HQQDPBNHGNK()
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.Custom)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000E85 RID: 3717 RVA: 0x00073F98 File Offset: 0x00072198
	private bool JIMHQOQEPEE()
	{
		if (!base.enabled)
		{
			return false;
		}
		CFDMNELIJLO component = base.GetComponent<CFDMNELIJLO>();
		return !(component == null) && component.IQKKIGIKGDN();
	}

	// Token: 0x06000E86 RID: 3718 RVA: 0x00008D71 File Offset: 0x00006F71
	private void DEQQINBKNLL(bool GKHHCNCGLCD)
	{
		if (this.PPOBGMJPDKN() && (!GKHHCNCGLCD || EMENMKHBPQE.GMDQCMCJEQI == EMENMKHBPQE.EGIKELMMQOO.Controller))
		{
			this.IEPGMNLKDIJ(GKHHCNCGLCD);
		}
	}

	// Token: 0x06000E87 RID: 3719 RVA: 0x00008CA4 File Offset: 0x00006EA4
	private void QGNEKNMJLID()
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnClick)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000E88 RID: 3720 RVA: 0x00008D8D File Offset: 0x00006F8D
	private void NLFHDFBHPLN()
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnMouseOut)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000E89 RID: 3721 RVA: 0x00008DB0 File Offset: 0x00006FB0
	private void QINFLJQBCIK()
	{
		if (this.GNMMJQMQOJI() && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnClick)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000E8A RID: 3722 RVA: 0x00073FC8 File Offset: 0x000721C8
	private void IEPGMNLKDIJ(bool IFFGDNBQHLO)
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnMouseOver)
		{
			if (this.FIBJMBNNPBQ == IFFGDNBQHLO)
			{
				return;
			}
			this.FIBJMBNNPBQ = IFFGDNBQHLO;
		}
		if (this.JIMHQOQEPEE() && ((IFFGDNBQHLO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnMouseOver) || (!IFFGDNBQHLO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.Custom)))
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000E8B RID: 3723 RVA: 0x00074028 File Offset: 0x00072228
	private void MJGODCPDOJM(bool FJOEKDCLKIO)
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.Custom)
		{
			if (this.FIBJMBNNPBQ == FJOEKDCLKIO)
			{
				return;
			}
			this.FIBJMBNNPBQ = FJOEKDCLKIO;
		}
		if (this.JGHBGBGNHLJ() && ((FJOEKDCLKIO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnMouseOut) || (!FJOEKDCLKIO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnMouseOut)))
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000E8C RID: 3724 RVA: 0x00008DDA File Offset: 0x00006FDA
	private void LMIJQMCBOFB()
	{
		if (this.JIMHQOQEPEE() && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnClick)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000E8D RID: 3725 RVA: 0x00008E04 File Offset: 0x00007004
	private void OnDisable()
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnDisable)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000E8E RID: 3726 RVA: 0x00074088 File Offset: 0x00072288
	private void DFQPBJJPHKH(bool FJOEKDCLKIO)
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnMouseOver)
		{
			if (this.FIBJMBNNPBQ == FJOEKDCLKIO)
			{
				return;
			}
			this.FIBJMBNNPBQ = FJOEKDCLKIO;
		}
		if (this.PPOBGMJPDKN() && ((FJOEKDCLKIO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnRelease) || (!FJOEKDCLKIO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnMouseOut)))
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000E8F RID: 3727 RVA: 0x000740E8 File Offset: 0x000722E8
	private bool EDJDMEEHDLM()
	{
		if (!base.enabled)
		{
			return false;
		}
		CFDMNELIJLO component = base.GetComponent<CFDMNELIJLO>();
		return component == null || component.GGBPLMICFHN;
	}

	// Token: 0x06000E90 RID: 3728 RVA: 0x00074118 File Offset: 0x00072318
	private void BNBEHQEHDKL(bool IFFGDNBQHLO)
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnMouseOver)
		{
			if (this.FIBJMBNNPBQ == IFFGDNBQHLO)
			{
				return;
			}
			this.FIBJMBNNPBQ = IFFGDNBQHLO;
		}
		if (this.BJFCGLCQLCG && ((IFFGDNBQHLO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnMouseOver) || (!IFFGDNBQHLO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnPress)))
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000E91 RID: 3729 RVA: 0x00074178 File Offset: 0x00072378
	private void PCHLIIFMFOB(bool IFFGDNBQHLO)
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnClick)
		{
			if (this.FIBJMBNNPBQ == IFFGDNBQHLO)
			{
				return;
			}
			this.FIBJMBNNPBQ = IFFGDNBQHLO;
		}
		if (this.GNMMJQMQOJI() && ((IFFGDNBQHLO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnClick) || (!IFFGDNBQHLO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnRelease)))
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000E92 RID: 3730 RVA: 0x00008E27 File Offset: 0x00007027
	private void OnClick()
	{
		if (this.BJFCGLCQLCG && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnClick)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000E93 RID: 3731 RVA: 0x00008E51 File Offset: 0x00007051
	public void MCOLENJKPHF()
	{
		IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
	}

	// Token: 0x06000E94 RID: 3732 RVA: 0x00008E51 File Offset: 0x00007051
	public void MLOIHHQMFBN()
	{
		IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
	}

	// Token: 0x06000E95 RID: 3733 RVA: 0x00008E51 File Offset: 0x00007051
	public void DGBQHPLBBIJ()
	{
		IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
	}

	// Token: 0x06000E96 RID: 3734 RVA: 0x00008CC7 File Offset: 0x00006EC7
	private void CQHEEEPPHQH()
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnRelease)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000E97 RID: 3735 RVA: 0x00008E04 File Offset: 0x00007004
	private void BJCFJQGGJMN()
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnDisable)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000E98 RID: 3736 RVA: 0x00008E6B File Offset: 0x0000706B
	private void BENFOPBIBDQ(bool GKHHCNCGLCD)
	{
		if (this.BJFCGLCQLCG && (!GKHHCNCGLCD || EMENMKHBPQE.GMDQCMCJEQI == (EMENMKHBPQE.EGIKELMMQOO)8))
		{
			this.QCEKMLKNKHP(GKHHCNCGLCD);
		}
	}

	// Token: 0x06000E99 RID: 3737 RVA: 0x000741D8 File Offset: 0x000723D8
	private void LOCHOKDIEOP(bool FJOEKDCLKIO)
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnMouseOver)
		{
			if (this.FIBJMBNNPBQ == FJOEKDCLKIO)
			{
				return;
			}
			this.FIBJMBNNPBQ = FJOEKDCLKIO;
		}
		if (this.PPOBGMJPDKN() && ((FJOEKDCLKIO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnMouseOver) || (!FJOEKDCLKIO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnRelease)))
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000E9A RID: 3738 RVA: 0x00008E87 File Offset: 0x00007087
	private void KLJCNBNJCPI(bool GKHHCNCGLCD)
	{
		if (this.JGHBGBGNHLJ() && (!GKHHCNCGLCD || EMENMKHBPQE.GMDQCMCJEQI == EMENMKHBPQE.EGIKELMMQOO.Touch))
		{
			this.IEPGMNLKDIJ(GKHHCNCGLCD);
		}
	}

	// Token: 0x06000E9B RID: 3739 RVA: 0x00008D2B File Offset: 0x00006F2B
	private void NJPBCHDJIDM()
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnEnable)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000E9C RID: 3740 RVA: 0x00008CA4 File Offset: 0x00006EA4
	private void KONKOQLPONQ()
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnClick)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000E9D RID: 3741 RVA: 0x00008E04 File Offset: 0x00007004
	private void HBJBLMLMEBD()
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnDisable)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000E9E RID: 3742 RVA: 0x00008CEA File Offset: 0x00006EEA
	private void HOQHKBCMPEK()
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnMouseOver)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000E9F RID: 3743 RVA: 0x00008EA3 File Offset: 0x000070A3
	private void OLLNOFNEEIL()
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.Auto)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000EA0 RID: 3744 RVA: 0x00008EC6 File Offset: 0x000070C6
	private void OEDIFGPQIKL()
	{
		if (this.DMNFEHMKIQC() && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnClick)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000EA1 RID: 3745 RVA: 0x00074238 File Offset: 0x00072438
	private void INCLLBKNLBL(bool IFFGDNBQHLO)
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnMouseOver)
		{
			if (this.FIBJMBNNPBQ == IFFGDNBQHLO)
			{
				return;
			}
			this.FIBJMBNNPBQ = IFFGDNBQHLO;
		}
		if (this.DMNFEHMKIQC() && ((IFFGDNBQHLO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnMouseOver) || (!IFFGDNBQHLO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnMouseOver)))
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000EA2 RID: 3746 RVA: 0x00008EF0 File Offset: 0x000070F0
	private void GJPGBCKQLDG()
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnPress)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000EA3 RID: 3747 RVA: 0x00074298 File Offset: 0x00072498
	private void FKIPQONIDGN(bool FJOEKDCLKIO)
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnEnable)
		{
			if (this.FIBJMBNNPBQ == FJOEKDCLKIO)
			{
				return;
			}
			this.FIBJMBNNPBQ = FJOEKDCLKIO;
		}
		if (this.JIMHQOQEPEE() && ((FJOEKDCLKIO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnClick) || (!FJOEKDCLKIO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.Auto)))
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000EA4 RID: 3748 RVA: 0x000742F8 File Offset: 0x000724F8
	private bool OKFGMBNFLFJ()
	{
		if (!base.enabled)
		{
			return true;
		}
		CFDMNELIJLO component = base.GetComponent<CFDMNELIJLO>();
		return component == null || component.IQKKIGIKGDN();
	}

	// Token: 0x06000EA5 RID: 3749 RVA: 0x00074328 File Offset: 0x00072528
	private void OGMDDNLPNLK(bool IFFGDNBQHLO)
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnClick)
		{
			if (this.FIBJMBNNPBQ == IFFGDNBQHLO)
			{
				return;
			}
			this.FIBJMBNNPBQ = IFFGDNBQHLO;
		}
		if (this.BJFCGLCQLCG && ((IFFGDNBQHLO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnClick) || (!IFFGDNBQHLO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnRelease)))
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000EA6 RID: 3750 RVA: 0x00073F98 File Offset: 0x00072198
	private bool ELNBBONFLEI()
	{
		if (!base.enabled)
		{
			return false;
		}
		CFDMNELIJLO component = base.GetComponent<CFDMNELIJLO>();
		return !(component == null) && component.IQKKIGIKGDN();
	}

	// Token: 0x06000EA7 RID: 3751 RVA: 0x00008CEA File Offset: 0x00006EEA
	private void OPGOQMDIIGQ()
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnMouseOver)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000EA8 RID: 3752 RVA: 0x00008EA3 File Offset: 0x000070A3
	private void KEGBCBGIHHJ()
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.Auto)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000EA9 RID: 3753 RVA: 0x00008E51 File Offset: 0x00007051
	public void GHGDBMDLDQE()
	{
		IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
	}

	// Token: 0x06000EAA RID: 3754 RVA: 0x00008F13 File Offset: 0x00007113
	private void JOFLHFQQCKG(bool GKHHCNCGLCD)
	{
		if (this.BJFCGLCQLCG && (!GKHHCNCGLCD || EMENMKHBPQE.GMDQCMCJEQI == EMENMKHBPQE.EGIKELMMQOO.Controller))
		{
			this.LJMOLEKDCLP(GKHHCNCGLCD);
		}
	}

	// Token: 0x06000EAB RID: 3755 RVA: 0x00008E51 File Offset: 0x00007051
	public void GGCJFGPFKFP()
	{
		IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
	}

	// Token: 0x06000EAC RID: 3756 RVA: 0x00008CA4 File Offset: 0x00006EA4
	private void CKQMBFKJMKH()
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnClick)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000EAD RID: 3757 RVA: 0x00008DDA File Offset: 0x00006FDA
	private void KJOPKJIKODI()
	{
		if (this.JIMHQOQEPEE() && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnClick)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000EAE RID: 3758 RVA: 0x00008F2F File Offset: 0x0000712F
	private void DPCNIIQGHKG(bool GKHHCNCGLCD)
	{
		if (this.PPOBGMJPDKN() && (!GKHHCNCGLCD || EMENMKHBPQE.GMDQCMCJEQI == (EMENMKHBPQE.EGIKELMMQOO)5))
		{
			this.LJMOLEKDCLP(GKHHCNCGLCD);
		}
	}

	// Token: 0x06000EAF RID: 3759 RVA: 0x00008D2B File Offset: 0x00006F2B
	private void NDFNCDDDJPN()
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnEnable)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000EB0 RID: 3760 RVA: 0x00008F4B File Offset: 0x0000714B
	private void JJMOCEOEMNM(bool GKHHCNCGLCD)
	{
		if (this.ELNBBONFLEI() && (!GKHHCNCGLCD || EMENMKHBPQE.GMDQCMCJEQI == (EMENMKHBPQE.EGIKELMMQOO)5))
		{
			this.LJMOLEKDCLP(GKHHCNCGLCD);
		}
	}

	// Token: 0x06000EB1 RID: 3761 RVA: 0x00008E51 File Offset: 0x00007051
	public void FFLIIMBBBPO()
	{
		IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
	}

	// Token: 0x06000EB2 RID: 3762 RVA: 0x00008CA4 File Offset: 0x00006EA4
	private void EINPCFNDKKJ()
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnClick)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000EB3 RID: 3763 RVA: 0x00074388 File Offset: 0x00072588
	private void JCCMBIHCLCD(bool FJOEKDCLKIO)
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnDisable)
		{
			if (this.FIBJMBNNPBQ == FJOEKDCLKIO)
			{
				return;
			}
			this.FIBJMBNNPBQ = FJOEKDCLKIO;
		}
		if (this.OKFGMBNFLFJ() && ((FJOEKDCLKIO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.Auto) || (!FJOEKDCLKIO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnMouseOut)))
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000EB4 RID: 3764 RVA: 0x000743E8 File Offset: 0x000725E8
	private bool FMNMCPLDMKE()
	{
		if (!base.enabled)
		{
			return true;
		}
		CFDMNELIJLO component = base.GetComponent<CFDMNELIJLO>();
		return !(component == null) && component.IQKKIGIKGDN();
	}

	// Token: 0x06000EB5 RID: 3765 RVA: 0x00008EA3 File Offset: 0x000070A3
	private void EBIJMQIMQOF()
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.Auto)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000EB6 RID: 3766 RVA: 0x00008F67 File Offset: 0x00007167
	private void MOHCCIOJOMB(bool GKHHCNCGLCD)
	{
		if (this.JIMHQOQEPEE() && (!GKHHCNCGLCD || EMENMKHBPQE.GMDQCMCJEQI == (EMENMKHBPQE.EGIKELMMQOO)5))
		{
			this.BDLILJEGCNB(GKHHCNCGLCD);
		}
	}

	// Token: 0x06000EB7 RID: 3767 RVA: 0x00074418 File Offset: 0x00072618
	private void OOMNIDEGEHP(bool FJOEKDCLKIO)
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnClick)
		{
			if (this.FIBJMBNNPBQ == FJOEKDCLKIO)
			{
				return;
			}
			this.FIBJMBNNPBQ = FJOEKDCLKIO;
		}
		if (this.JIMHQOQEPEE() && ((FJOEKDCLKIO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnClick) || (!FJOEKDCLKIO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnMouseOver)))
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000EB8 RID: 3768 RVA: 0x00008DB0 File Offset: 0x00006FB0
	private void MIGOIHCOBNB()
	{
		if (this.GNMMJQMQOJI() && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnClick)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000EB9 RID: 3769 RVA: 0x00008EF0 File Offset: 0x000070F0
	private void EOLBEDLCPHQ()
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnPress)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000EBA RID: 3770 RVA: 0x00008F83 File Offset: 0x00007183
	private void EQMFGQBEEJC(bool GKHHCNCGLCD)
	{
		if (this.BJFCGLCQLCG && (!GKHHCNCGLCD || EMENMKHBPQE.GMDQCMCJEQI == (EMENMKHBPQE.EGIKELMMQOO)3))
		{
			this.KDDLPPJHQDB(GKHHCNCGLCD);
		}
	}

	// Token: 0x06000EBB RID: 3771 RVA: 0x00008EA3 File Offset: 0x000070A3
	private void Start()
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.Auto)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000EBC RID: 3772 RVA: 0x00074328 File Offset: 0x00072528
	private void QHEOCGFHCJF(bool IFFGDNBQHLO)
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnClick)
		{
			if (this.FIBJMBNNPBQ == IFFGDNBQHLO)
			{
				return;
			}
			this.FIBJMBNNPBQ = IFFGDNBQHLO;
		}
		if (this.BJFCGLCQLCG && ((IFFGDNBQHLO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnClick) || (!IFFGDNBQHLO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnRelease)))
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000EBD RID: 3773 RVA: 0x00008D4E File Offset: 0x00006F4E
	private void PDQHBNHDLEB()
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.Custom)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000EBE RID: 3774 RVA: 0x00074478 File Offset: 0x00072678
	private bool GNMMJQMQOJI()
	{
		if (!base.enabled)
		{
			return true;
		}
		CFDMNELIJLO component = base.GetComponent<CFDMNELIJLO>();
		return component == null || component.EFBQLPLOMQB();
	}

	// Token: 0x06000EBF RID: 3775 RVA: 0x00008EA3 File Offset: 0x000070A3
	private void MKQFKMQDGPE()
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.Auto)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000EC0 RID: 3776 RVA: 0x00008F9F File Offset: 0x0000719F
	private void GGMINIPOKJI()
	{
		if (this.OKFGMBNFLFJ() && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnClick)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000EC1 RID: 3777 RVA: 0x00008E51 File Offset: 0x00007051
	public void LLQQDJIDGNJ()
	{
		IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
	}

	// Token: 0x06000EC2 RID: 3778 RVA: 0x000744A8 File Offset: 0x000726A8
	private void BDLILJEGCNB(bool IFFGDNBQHLO)
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnMouseOver)
		{
			if (this.FIBJMBNNPBQ == IFFGDNBQHLO)
			{
				return;
			}
			this.FIBJMBNNPBQ = IFFGDNBQHLO;
		}
		if (this.ELNBBONFLEI() && ((IFFGDNBQHLO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnClick) || (!IFFGDNBQHLO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnDisable)))
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000EC3 RID: 3779 RVA: 0x00074508 File Offset: 0x00072708
	private void DBHJMFECHOJ(bool FJOEKDCLKIO)
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnMouseOut)
		{
			if (this.FIBJMBNNPBQ == FJOEKDCLKIO)
			{
				return;
			}
			this.FIBJMBNNPBQ = FJOEKDCLKIO;
		}
		if (this.FMNMCPLDMKE() && ((FJOEKDCLKIO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnClick) || (!FJOEKDCLKIO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnDisable)))
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000EC4 RID: 3780 RVA: 0x00074568 File Offset: 0x00072768
	private void KDDLPPJHQDB(bool IFFGDNBQHLO)
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnMouseOver)
		{
			if (this.FIBJMBNNPBQ == IFFGDNBQHLO)
			{
				return;
			}
			this.FIBJMBNNPBQ = IFFGDNBQHLO;
		}
		if (this.JGHBGBGNHLJ() && ((IFFGDNBQHLO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnClick) || (!IFFGDNBQHLO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnPress)))
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000EC5 RID: 3781 RVA: 0x000745C8 File Offset: 0x000727C8
	private void LJMOLEKDCLP(bool IFFGDNBQHLO)
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnMouseOver)
		{
			if (this.FIBJMBNNPBQ == IFFGDNBQHLO)
			{
				return;
			}
			this.FIBJMBNNPBQ = IFFGDNBQHLO;
		}
		if (this.BJFCGLCQLCG && ((IFFGDNBQHLO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnMouseOver) || (!IFFGDNBQHLO && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnMouseOut)))
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x1700002F RID: 47
	// (get) Token: 0x06000EC6 RID: 3782 RVA: 0x000740E8 File Offset: 0x000722E8
	private bool BJFCGLCQLCG
	{
		get
		{
			if (!base.enabled)
			{
				return false;
			}
			CFDMNELIJLO component = base.GetComponent<CFDMNELIJLO>();
			return component == null || component.GGBPLMICFHN;
		}
	}

	// Token: 0x06000EC7 RID: 3783 RVA: 0x00008CC7 File Offset: 0x00006EC7
	private void IKDKGEBOJBK()
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnRelease)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000EC8 RID: 3784 RVA: 0x00008FC9 File Offset: 0x000071C9
	private void FKDKLOCBKQM(bool GKHHCNCGLCD)
	{
		if (this.JGHBGBGNHLJ() && (!GKHHCNCGLCD || EMENMKHBPQE.GMDQCMCJEQI == EMENMKHBPQE.EGIKELMMQOO.Touch))
		{
			this.BNBEHQEHDKL(GKHHCNCGLCD);
		}
	}

	// Token: 0x06000EC9 RID: 3785 RVA: 0x00008FE5 File Offset: 0x000071E5
	private void POQODIFNQPB(bool GKHHCNCGLCD)
	{
		if (this.JIMHQOQEPEE() && (!GKHHCNCGLCD || EMENMKHBPQE.GMDQCMCJEQI == EMENMKHBPQE.EGIKELMMQOO.Touch))
		{
			this.KDDLPPJHQDB(GKHHCNCGLCD);
		}
	}

	// Token: 0x06000ECA RID: 3786 RVA: 0x00008EC6 File Offset: 0x000070C6
	private void CPFPLCDFCCQ()
	{
		if (this.DMNFEHMKIQC() && this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnClick)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x06000ECB RID: 3787 RVA: 0x00008CC7 File Offset: 0x00006EC7
	private void BBDPHLPLFCP()
	{
		if (this.ILLDIKBCNMC == KGJGOEICIJE.QCDBPHFLEII.OnRelease)
		{
			IKBQNBHOJJB.LKHCJLDFLEJ(this.HJNQLOIKFFO, this.KKKLPHMOKBP, this.EPFDOOIODDN);
		}
	}

	// Token: 0x04000264 RID: 612
	public AudioClip HJNQLOIKFFO;

	// Token: 0x04000265 RID: 613
	public KGJGOEICIJE.QCDBPHFLEII ILLDIKBCNMC;

	// Token: 0x04000266 RID: 614
	[Range(0f, 1f)]
	public float KKKLPHMOKBP = 1f;

	// Token: 0x04000267 RID: 615
	[Range(0f, 2f)]
	public float EPFDOOIODDN = 1f;

	// Token: 0x04000268 RID: 616
	private bool FIBJMBNNPBQ;

	// Token: 0x0200006D RID: 109
	public enum QCDBPHFLEII
	{
		// Token: 0x0400026A RID: 618
		OnClick,
		// Token: 0x0400026B RID: 619
		OnMouseOver,
		// Token: 0x0400026C RID: 620
		OnMouseOut,
		// Token: 0x0400026D RID: 621
		OnPress,
		// Token: 0x0400026E RID: 622
		OnRelease,
		// Token: 0x0400026F RID: 623
		Custom,
		// Token: 0x04000270 RID: 624
		OnEnable,
		// Token: 0x04000271 RID: 625
		OnDisable,
		// Token: 0x04000272 RID: 626
		Auto
	}
}
